type              : agent.plugin
label             : "splunk_check--{{ inventory_hostname }}"
period            : "{{ splunk_check_period | default(60) }}"
timeout           : "{{ splunk_check_timeout | default(30) }}"
disabled          : "false"
details     :
    file    : run_plugin_in_venv.sh
    args    : ["/usr/lib/rackspace-monitoring-agent/plugins/splunk_check.py", "--container", "{{ groups['rsyslog'] }}"]
alarms:
    splunk_daemon_status :
        label                   : splunk_daemon_status--"{{ inventory_hostname }}"
        notification_plan_id    : "npManaged"
        disabled                : false
        criteria                : |
            :set consecutiveCount=3
            if (metric["splunk_active"] != 1) {
                return new AlarmStatus(CRITICAL, "The Splunk forwarder is not running. Try to restart the forwarder with service splunk restart.");
            }
    splunk_connection_status :
        label                   : splunk_connection_status--"{{ inventory_hostname }}"
        notification_plan_id    : "npManaged"
        disabled                : false
        criteria                : |
            :set consecutiveCount=3
            if (metric["splunk_connected"] != 1) {
                return new AlarmStatus(CRITICAL, "The Splunk forwarder is not connected to home base. Please investigate!");
            }
    splunk_target_log_status :
        label                   : splunk_target_log_status--"{{ inventory_hostname }}"
        notification_plan_id    : "npManaged"
        disabled                : false
        criteria                : |
            :set consecutiveCount=3
            if (metric["splunk_shipping"] != 1) {
                return new AlarmStatus(CRITICAL, "The log file Splunk monitors is not updating. Please investigate rsyslog.");
            }
